### ISSUE TITLE
OnCache 方法不支持指定路径的解析和缓存

### ISSUE THREAD

**Issue by InsectQY** [Pircate/RxNetwork#1]
Hello，我看了下你的实现，思路很好。
但是你在
```
public func request() -> Single<C> {
    return target.request().map(C.self).storeCachedObject(for: target)
}
```
这个方法中默认是拿到返回数据的根路径去解析和缓存的，假如我不想缓存根路径的模型，只想缓存某个路径的模型，是不支持的。
我知道可以把路径作为参数也写到这个 ```request``` 方法中，但是这样一来方法的语义看起来就没有那么优雅了。

**Comment by Pircate** [comment]
没太明白你的意思，缓存某个路径的模型是指将模型缓存到指定的路径？

**Comment by Pircate** [comment]
这个可以自己再封装一层的，可以查看最新Demo里的[OnCache+Demo.swift](https://github.com/Pircate/RxNetwork/blob/master/Example/RxNetwork/OnCache%2BDemo.swift)文件。
毕竟每个人的需求不一样，传个keyPath也不一定能解决问题。
