### ISSUE TITLE
一些关于 podspec 文件的小建议。

### ISSUE THREAD

**Issue by InsectQY** [Pircate/RxNetwork#2]
1.  可以把  `swift_version` 改到 "4.2"，不然新安装库 Xcode 都会提示 convert 。
2. `ios.deployment_target` 可以从 8.0 开始支持，有些人还是会有从 8.0 开始适配的需求的。另外一个 CleanJSON 的库也可以改到从8.0开始。

这两个包括 CleanJSON 我都用私有库测试过，直接改就行，不用动主工程的任何代码。虽然修改 podspec 用私有库也能满足自己的需求，但还是支持一下官方比较好。

**Comment by Pircate** [comment]
swift 版本我会改下，但是现在基本都是从 9.0 开始了吧。

**Comment by InsectQY** [comment]
哈哈，我是想既然可以不花费任何精力支持 8.0，何乐而不为呢
