### ISSUE TITLE
Endpoint的自定义

### ISSUE THREAD

**Issue by WS-Vincent** [Pircate/RxNetwork#3]
let endpointClosure = { target -> Endpoint in
            MoyaProvider.defaultEndpointMapping(for: target).replacing(task: configuration.taskClosure(target))
        } 这个地方用的默认的Endpoint    
要改变的话 是不是只能用Network.default.provider去设置了

**Comment by Pircate** [comment]
你需要改什么呢？

**Comment by WS-Vincent** [comment]
早上好，大佬。后来想想Endpoint也是对target做了相应操作转换，在target里面做也是一样。😀
